fail_fast: true

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=500"]
        exclude: >
          (?x)^(
            package-lock\.json|pnpm-lock\.yaml
          )$
      - id: fix-byte-order-marker
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: debug-statements
      - id: detect-private-key

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.8
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: local
    hooks:
      # Lint frontend (cross‑platform via pnpm -C)
      - id: frontend-lint
        name: Run frontend lint
        entry: pnpm
        args: ["-C", "frontend", "run", "lint"]
        language: system
        files: ^frontend/.*\.(js|jsx|ts|tsx)$
        pass_filenames: false

      # Prettier
      - id: frontend-prettier
        name: Run Prettier on frontend files
        entry: pnpm
        args: ["-C", "frontend", "run", "prettier"]
        language: system
        files: ^frontend/.*\.(js|jsx|ts|tsx)$
        pass_filenames: false

      # Type-check
      - id: frontend-tsc
        name: Run frontend tsc
        entry: pnpm
        args: ["-C", "frontend", "run", "tsc"]
        language: system
        files: ^frontend/.*\.(ts|tsx)$
        pass_filenames: false

      # - id: generate-openapi-schema
      #   name: generate OpenAPI schema
      #   entry: uv
      #   args: ["run", "--directory", "backend", "python", "src/commands/generate_openapi_schema.py"]
      #   language: system
      #   # Only run OpenAPI schema generation if schemas.py, main.py or package version have changed:
      #   files: (main\.py$|schemas\.py$|pyproject\.toml)
      #   pass_filenames: false

      # # Generate frontend client when openapi.json changes
      # - id: generate-frontend-client
      #   name: Generate frontend client
      #   entry: pnpm
      #   args: ["-C", "frontend", "run", "generate-client"]
      #   language: system
      #   files: ^openapi\.json$
      #   pass_filenames: false
