name: 🚀 Feature Request
description: Suggest a new feature for Plant Assistant
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please verify these steps before submitting
      options:
        - label: I have searched existing issues to ensure this feature hasn't been requested
          required: true
        - label: I have considered if this fits the project's scope and goals
          required: true

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What type of feature is this?
      options:
        - Plant Management
        - User Interface
        - API Enhancement
        - Authentication/Security
        - Performance
        - Documentation
        - Developer Tools
        - Other
    validations:
      required: true

  - type: textarea
    id: summary
    attributes:
      label: Feature Summary
      description: A brief, clear description of the feature
      placeholder: Summarize your feature request in 1-2 sentences...
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: |
        Is your feature request related to a problem? Please describe.
        A clear and concise description of what the problem is.
        Ex. I'm always frustrated when [...]
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: |
        A clear and concise description of what you want to happen.
        Include any specific implementation details if you have them.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What alternatives have you considered?
      placeholder: |
        A clear and concise description of any alternative solutions
        or features you've considered.

  - type: textarea
    id: benefits
    attributes:
      label: Benefits
      description: What are the benefits of this feature?
      placeholder: |
        - Who would benefit from this feature?
        - How would it improve the user experience?
        - Any performance or efficiency gains?

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature?
      options:
        - Low - Nice to have
        - Medium - Would be helpful
        - High - Important for workflow
        - Critical - Blocking major use case
    validations:
      required: true

  - type: textarea
    id: implementation
    attributes:
      label: Implementation Ideas
      description: Any ideas on how this could be implemented?
      placeholder: |
        If you have ideas about implementation:
        - Frontend changes needed
        - Backend changes needed
        - Database changes needed
        - External services/APIs needed

  - type: textarea
    id: mockups
    attributes:
      label: Mockups/Examples
      description: Any mockups, wireframes, or examples
      placeholder: |
        If you have mockups, wireframes, or examples from other applications,
        please include them here.

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Are you willing to contribute to this feature?
      options:
        - label: I'd be willing to implement this feature
        - label: I'd be willing to help test this feature
        - label: I'd be willing to help with documentation

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context or information about the feature request
