// This file is auto-generated by @hey-api/openapi-ts

export type HTTPValidationError = {
  detail?: Array<ValidationError>;
};

export type LoginIn = {
  email: string;
  password: string;
};

export type RegisterIn = {
  email: string;
  password: string;
  name?: string | null;
};

export type ValidationError = {
  loc: Array<string | number>;
  msg: string;
  type: string;
};

export type RegisterData = {
  body: RegisterIn;
};

export type RegisterResponse = unknown;

export type RegisterError = HTTPValidationError;

export type LoginData = {
  body: LoginIn;
};

export type LoginResponse = unknown;

export type LoginError = HTTPValidationError;

export type LoginGoogleData = {
  query?: {
    mode?: string | null;
  };
};

export type LoginGoogleResponse = unknown;

export type LoginGoogleError = HTTPValidationError;

export type CallbackGoogleData = {
  query?: {
    mode?: string | null;
  };
};

export type CallbackGoogleResponse = unknown;

export type CallbackGoogleError = HTTPValidationError;

export type RefreshResponse = unknown;

export type RefreshError = unknown;

export type LogoutResponse = unknown;

export type LogoutError = unknown;

export type MeResponse = unknown;

export type MeError = unknown;
